### ISSUE TITLE
Maintaining Test Schema fails with transactional_capybara

### ISSUE THREAD

**Issue by tomdracz** [iangreenleaf/transactional_capybara#6]
Using v 0.1.0

My rails_helper is set as follows (relevant parts only)

```
ENV["RAILS_ENV"] ||= 'test'
require 'spec_helper'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'capybara/rspec'
require 'capybara/rails'
require 'capybara/poltergeist'
require 'transactional_capybara/rspec'

ActiveRecord::Migration.maintain_test_schema!
```

Running test suite when migrations were NOT run beforehand (hitting maitain_test_schema! method) results in connection fail:

`/Users/tom/.rvm/gems/ruby-2.3.1@hanover/gems/activerecord-4.2.5/lib/active_record/connection_adapters/mysql2_adapter.rb:74:in `quote_string': undefined method `escape' for nil:NilClass (NoMethodError)`

It seems that @connection var ends up being nil at some point in the process.

You can replicate by calling maintain_test_schema! AFTER requiring transactional_capybara

If I remove transactional_capybara OR move maintain_test_schema before requiring it, everything is dandy.

Tried PR #2 locally to see whether it would solve the issue as it was one possibility, but no dice.

Easy solution is to mention in the Readme that quirk but it seems like there's bigger underlying issue somewhere there.

**Comment by tomdracz** [comment]
@iangreenleaf thoughts?

**Comment by iangreenleaf** [comment]
Sorry for not responding sooner! I've had a busy month so this kept getting bumped. I have no idea what's going on there. I wonder if `maintain_test_schema!` is resetting the connection or something. If you feel like doing some debugging I'd love to hear about any findings.

An update to the Readme would also be great. Feel like creating a pull request to add that?

**Comment by tomdracz** [comment]
Hey @iangreenleaf . Tried to debug the issue but it looks like a pyramid of doom that eventually leads to failure in low-level mysql2 adapter. In Rails 5 I actually end up with connection var being present but mysql2 still failing to detect connection.
I've submitted PR for readme change for now to hopefully protect other users from the pains I've encountered!
