### ISSUE TITLE
DatabaseCleaner.clean happening before wait_for_ajax(page)

### ISSUE THREAD

**Issue by canoeberry** [iangreenleaf/transactional_capybara#8]
I have the following in spec_helper, per your excellent instructions, but the wait_for_ajax call is coming last, which is decidedly too late.

Can you spot my mistake?

  # wait for ajax at the end
    config.after(:each) do
      TransactionalCapybara::AjaxHelpers.wait_for_ajax(page)
    end
  
    # configure the cleaner stuff AFTER TransactionalCapybara above so the ordering is right.
    config.before(:suite) do
      DatabaseCleaner.clean_with(:truncation)
    end
  
    config.before(:each) do
      DatabaseCleaner.strategy = :transaction
    end
  
    config.before(:each, js: true) do
      DatabaseCleaner.strategy = :truncation
    end
  
    config.before(:each) do
      DatabaseCleaner.start
    end
  
    config.after(:each) do
      DatabaseCleaner.clean
    end

**Comment by canoeberry** [comment]
I suppose I should have tried the exact opposite ordering, which seemed to work, but ... Maybe it's rails version dependent.

I'm on 4.2.8.

**Comment by iangreenleaf** [comment]
Huh, so what worked for you was something like this?

```
config.after(:each) do
  DatabaseCleaner.clean
end

config.after(:each) do
  TransactionalCapybara::AjaxHelpers.wait_for_ajax(page)
end
```

To double-check, you could also try this to make sure the results look the same, since this is what we *think* should be happening:

```
config.after(:each) do
  TransactionalCapybara::AjaxHelpers.wait_for_ajax(page)
  DatabaseCleaner.clean
end
```

**Comment by canoeberry** [comment]
It's the same ... as far as I can tell. My test doesn't succeed anymore because I deleted some  home grown stuff and want to use just yours, but, I didn't get the annoying "DB connection already in use" error.

**Comment by canoeberry** [comment]
OK - so I got things working but had to put things in the opposite order as you described in your page. I am not sure why. But I will close this now.

Thanks for your help.

**Comment by iangreenleaf** [comment]
Thanks for letting me know! I sure thought the way I was describing was the proper way, but now I'm not so sure. RSpec [documents the run order of different types of blocks](https://relishapp.com/rspec/rspec-core/docs/hooks/before-and-after-hooks#%60before%60/%60after%60-blocks-are-run-in-order), but none of the examples deal with multiple blocks of the same type, so possibly that behavior is undefined. I've updated the README to suggest putting both in the same block, since that will eliminate any ambiguity.
